#ifndef __wkdeploy_definitions_h
#define __wkdeploy_definitions_h

/*
 * This file is machine-generated by the infuser tool.
 * Do not edit.
 */

#include "types.h"

void wkdeploy_native_handler(dj_global_id id);

// Class definitions
// WKDeploy
#define WKDEPLOY_CDEF_WKDeploy 0
typedef struct _WKDEPLOY_STRUCT_WKDeploy {
} __attribute__ ((__packed__)) WKDEPLOY_STRUCT_WKDeploy;


// Method definitions
#define WKDEPLOY_MDEF_void_main_java_lang_String__ 0
#define WKDEPLOY_MDEF_void_createVirtualWuObjects 1


#endif

