GESTURE_FIST = 0
GESTURE_SWIPE_LEFT = 1
GESTURE_SWIPE_RIGHT = 2
GESTURE_THUMB_UP = 3
GESTURE_THUMB_DOWN = 4
GESTURE_TWO_FINGERS_PINCH_OPEN = 5
GESTURE_WAVE = 6
GESTURE_DIRTY = 7

MODE_VIDEO = 0
MODE_HANGOUT = 1
MODE_1ST_FLOOR = 2
MODE_3RD_FLOOR = 3
MODE_KITCHEN = 4