#ifndef RTC_SAFETYCHECKS_FAIL_H
#define RTC_SAFETYCHECKS_FAIL_H

#include <stdint.h>

void rtc_safety_abort_with_error(uint8_t error);

#define RTC_SAFETYCHECK_METHOD_SHOULD_END_IN_BRANCH_OR_RETURN          0
#define RTC_SAFETYCHECK_INT_STACK_UNDERFLOW                            1
#define RTC_SAFETYCHECK_REF_STACK_UNDERFLOW                            2
#define RTC_SAFETYCHECK_INT_STACK_OVERFLOW                             3
#define RTC_SAFETYCHECK_REF_STACK_OVERFLOW                             4
#define RTC_SAFETYCHECK_STACK_NOT_EMPTY_AFTER_RETURN                   5
#define RTC_SAFETYCHECK_STACK_NOT_EMPTY_AT_BRANCH                      6
#define RTC_SAFETYCHECK_STACK_NOT_EMPTY_AT_BRANCHTARGET                7
#define RTC_SAFETYCHECK_BRANCHTARGET_COUNT_MISMATCH_WITH_METHOD_HEADER 8
#define RTC_SAFETYCHECK_BRANCH_TO_NONEXISTANT_BRTARGET                 9
#define RTC_SAFETYCHECK_STORE_TO_NONEXISTANT_LOCAL_VARIABLE           10
#define RTC_SAFETYCHECK_STORE_TO_NONEXISTANT_STATIC_VARIABLE          11
#define RTC_SAFETYCHECK_ILLEGAL_REFERENCED_INFUSION_IN_GLOBAL_ID      12
#define RTC_SAFETYCHECK_REFERENCE_TO_NONEXISTANT_METHODIMPL           13
#define RTC_SAFETYCHECK_RETURN_INSTRUCTION_DOESNT_MATCH_RETURN_TYPE   14
#define RTC_SAFETYCHECK_RETURN_INCORRECT_METHOD_HEADER                15
#define RTC_SAFETYCHECK_NOT_ENOUGH_SPACE_IN_FRAME_FOR_LW_CALL         16

#endif // RTC_SAFETYCHECKS_FAIL_H
