#ifndef RTC_SAFETYCHECKS_VM_PART_H
#define RTC_SAFETYCHECKS_VM_PART_H

#include <stdint.h>

extern uint16_t rtc_safety_heap_lowbound;
void rtc_safety_mark_heap_bounds();

void rtc_safety_abort_with_error(uint8_t error);

#define RTC_SAFETY_MIN_GAP_BETWEEN_STACK_AND_HEAP                     100

#define RTC_SAFETY_TRANSLATIONCHECK_METHOD_SHOULD_END_IN_BRANCH_OR_RETURN           0
#define RTC_SAFETY_TRANSLATIONCHECK_BRANCH_TO_NONEXISTANT_BRTARGET                  1
#define RTC_SAFETY_TRANSLATIONCHECK_BRANCHTARGET_COUNT_MISMATCH_WITH_METHOD_HEADER  2
#define RTC_SAFETY_TRANSLATIONCHECK_TRANSLATED_LIGHTWEIGHTMETHOD_NOT_FOUND          3
#define RTC_SAFETY_TRANSLATIONCHECK_NO_IMPLEMENTATION_FOUND_FOR_INVOKESTATIC        4
#define RTC_SAFETY_TRANSLATIONCHECK_STACK_NOT_EMPTY_AFTER_RETURN_OR_BRANCH          5
#define RTC_SAFETY_TRANSLATIONCHECK_INCORRECT_METHOD_HEADER                         6
#define RTC_SAFETY_TRANSLATIONCHECK_NOT_ENOUGH_SPACE_IN_FRAME_FOR_LW_CALL           7
#define RTC_SAFETY_TRANSLATIONCHECK_STORE_TO_NONEXISTANT_LOCAL_VARIABLE             8
#define RTC_SAFETY_TRANSLATIONCHECK_ILLEGAL_REFERENCED_INFUSION_IN_GLOBAL_ID        9
#define RTC_SAFETY_TRANSLATIONCHECK_STORE_TO_NONEXISTANT_STATIC_VARIABLE           10
#define RTC_SAFETY_TRANSLATIONCHECK_INT_STACK_UNDERFLOW                            11
#define RTC_SAFETY_TRANSLATIONCHECK_REF_STACK_UNDERFLOW                            12
#define RTC_SAFETY_TRANSLATIONCHECK_INT_STACK_OVERFLOW                             13
#define RTC_SAFETY_TRANSLATIONCHECK_REF_STACK_OVERFLOW                             14
#define RTC_SAFETY_RUNTIMECHECK_NO_IMPLEMENTATION_FOUND_FOR_INVOKEVIRTUAL          15
#define RTC_SAFETY_RUNTIMECHECK_VIRTUAL_IMPLEMENTATION_SIGNATURE_MISMATCH          16
#define RTC_SAFETY_RUNTIMECHECK_ILLEGAL_MEMORY_ACCESS                              17
#define RTC_SAFETY_RUNTIMECHECK_NATIVE_STACK_OVERFLOW                              18

#endif // RTC_SAFETYCHECKS_VM_PART_H
