RADIO_ADDRESS_LEN_ZW = 1
RADIO_ADDRESS_LEN_ZB = 2
RADIO_ADDRESS_LEN_IP = 4

STOP_MODE = (0, "STOP")
ADD_MODE = (1, "ADD")
DEL_MODE = (2, "DELTE")

MULT_PROTO_IP_PORT = 9001

# Acceptable payload format
# 4 bytes: destionation DID
# 4 bytes: source DID
# 1 byte: message type
# 1 byte: message subtype
# rest byte(s): payload
MULT_PROTO_LEN_DID              = 4
MULT_PROTO_LEN_MSG_TYPE         = 1
MULT_PROTO_LEN_MSG_SUBTYPE      = 1

MULT_PROTO_HEADER_FORMAT = (MULT_PROTO_LEN_DID, MULT_PROTO_LEN_DID, MULT_PROTO_LEN_MSG_TYPE, MULT_PROTO_LEN_MSG_SUBTYPE)
MULT_PROTO_DEST_BYTE_OFFSET     = 0
MULT_PROTO_SRC_BYTE_OFFSET      = MULT_PROTO_DEST_BYTE_OFFSET + MULT_PROTO_LEN_DID
MULT_PROTO_MSG_TYPE_BYTE_OFFSET = MULT_PROTO_SRC_BYTE_OFFSET + MULT_PROTO_LEN_DID
MULT_PROTO_MSG_SUBTYPE_BYTE_OFFSET = MULT_PROTO_MSG_TYPE_BYTE_OFFSET + MULT_PROTO_LEN_MSG_TYPE
MULT_PROTO_MSG_PAYLOAD_BYTE_OFFSET = MULT_PROTO_MSG_SUBTYPE_BYTE_OFFSET + MULT_PROTO_LEN_MSG_SUBTYPE


MULT_PROTO_MSG_TYPE_RAD         = 0x00
MULT_PROTO_MSG_SUBTYPE_RAD_ADD  = 0x00
MULT_PROTO_MSG_SUBTYPE_RAD_DEL  = 0x01
MULT_PROTO_MSG_SUBTYPE_RAD_STOP = 0x02
MULT_PROTO_MSG_SUBTYPE_RAD_POLL = 0x03
MULT_PROTO_MSG_SUBTYPE_RAD_ACK  = 0x04
MULT_PROTO_MSG_SUBTYPE_RAD_NAK  = 0x05

MULT_PROTO_MSG_TYPE_DID         = 0x01
MULT_PROTO_MSG_SUBTYPE_DID_REQ  = 0x00
MULT_PROTO_MSG_SUBTYPE_DID_UPD  = 0x01
MULT_PROTO_MSG_SUBTYPE_DID_OFFR = 0x02
MULT_PROTO_MSG_SUBTYPE_DID_ACK  = 0x03
MULT_PROTO_MSG_SUBTYPE_DID_NAK  = 0x04

MULT_PROTO_MSG_TYPE_RPC         = 0x02
MULT_PROTO_MSG_SUBTYPE_RPC_CMD  = 0x00
MULT_PROTO_MSG_SUBTYPE_RPC_REP  = 0x01

MULT_PROTO_MSG_TYPE_FWD         = 0x03
MULT_PROTO_MSG_SUBTYPE_FWD      = 0x00
MULT_PROTO_MSG_SUBTYPE_FWD_ACK  = 0x01
MULT_PROTO_MSG_SUBTYPE_FWD_NAK  = 0x02

MULT_PROTO_MSG_TYPE_PFX         = 0x04
MULT_PROTO_MSG_SUBTYPE_PFX_REQ  = 0x00
MULT_PROTO_MSG_SUBTYPE_PFX_UPD  = 0x01
MULT_PROTO_MSG_SUBTYPE_PFX_ACK  = 0x02
MULT_PROTO_MSG_SUBTYPE_PFX_NAK  = 0x03

WKPF_COMMAND_MONITOR = 0xB5