#ifndef __helloworld_definitions_h
#define __helloworld_definitions_h

/*
 * This file is machine-generated by the infuser tool.
 * Do not edit.
 */

#include "types.h"

void helloworld_native_handler(dj_global_id id);

// Class definitions
// HelloWorld
#define HELLOWORLD_CDEF_HelloWorld 0
typedef struct _HELLOWORLD_STRUCT_HelloWorld {
} __attribute__ ((__packed__)) HELLOWORLD_STRUCT_HelloWorld;


// Method definitions
#define HELLOWORLD_MDEF_void_main_java_lang_String__ 0


#endif

