#ifndef __darjeeling3_definitions_h
#define __darjeeling3_definitions_h

/*
 * This file is machine-generated by the infuser tool.
 * Do not edit.
 */

#include "types.h"

void darjeeling3_native_handler(dj_global_id id);

// Class definitions
// javax.darjeeling.ConsoleOutputStream
#define DARJEELING3_CDEF_javax_darjeeling_ConsoleOutputStream 0
typedef struct _DARJEELING3_STRUCT_javax_darjeeling_ConsoleOutputStream {
} __attribute__ ((__packed__)) DARJEELING3_STRUCT_javax_darjeeling_ConsoleOutputStream;

// javax.darjeeling.Darjeeling
#define DARJEELING3_CDEF_javax_darjeeling_Darjeeling 1
typedef struct _DARJEELING3_STRUCT_javax_darjeeling_Darjeeling {
} __attribute__ ((__packed__)) DARJEELING3_STRUCT_javax_darjeeling_Darjeeling;


// Method definitions
#define DARJEELING3_MDEF_void_assertTrue_int_boolean 0
#define DARJEELING3_MDEF_void__print_java_lang_String 1
#define DARJEELING3_MDEF_int_getMemFree 2
#define DARJEELING3_MDEF_int_getNodeId 3
#define DARJEELING3_MDEF_int_random 4
#define DARJEELING3_MDEF_short_getNrThreads 5
#define DARJEELING3_MDEF_java_lang_Thread_getThread_short 6


#endif

